// lib/services/delivery_generation_service.dart
import 'package:get/get.dart';
import 'package:uuid/uuid.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../core/constants/app_constants.dart';
import '../core/utils/logger.dart';
import '../data/models/delivery_model.dart';
import '../data/models/sync_action_model.dart';
import '../data/models/time_slot_model.dart';
import 'connectivity_service.dart';
import 'local_storage_service.dart';

class DeliveryGenerationService extends GetxService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;
  final ConnectivityService _connectivity = Get.find<ConnectivityService>();

  String _deliveriesCol(String vid) =>
      '${AppConstants.colVendors}/$vid/${AppConstants.colDeliveries}';

  // ─────────────────────────────────────────────────────────────
  // PUBLIC API
  // ─────────────────────────────────────────────────────────────

  /// Called at midnight: pre-generates tomorrow's deliveries for ALL slots
  /// so they are ready in cache even if the engine hasn't ticked yet.
  /// Today's remaining slots are handled by the engine as each window opens.
  Future<int> generateTodayAndTomorrow(String vendorId) async {
    final today    = DateTime.now();
    final tomorrow = today.add(const Duration(days: 1));

    // Today: only slots that are currently open or already past (catch-up).
    // Future slots today will be generated by the engine at slot-start time.
    final generatedToday    = await generateForDate(vendorId, today,    onlyOpenOrPastSlots: true);
    // Tomorrow: pre-generate everything so it's ready in cache.
    final generatedTomorrow = await generateForDate(vendorId, tomorrow, onlyOpenOrPastSlots: false);

    return generatedToday + generatedTomorrow;
  }

  /// Generates deliveries for a specific calendar day.
  ///
  /// [onlyOpenOrPastSlots] — when true, skips slots whose start time is still
  /// in the future (they will be handled by the engine). When false (used for
  /// tomorrow's pre-generation), generates all slots regardless of time.
  Future<int> generateForDate(
      String vendorId,
      DateTime date, {
        bool onlyOpenOrPastSlots = true,
      }) async {
    final subscriptions = LocalStorageService.getSubscriptions()
        .where((s) => s.isActive)
        .toList();

    if (subscriptions.isEmpty) return 0;

    final customerMap = {
      for (final c in LocalStorageService.getCustomers()) c.id: c,
    };

    // Build a map of startTime → TimeSlotModel for fast lookup
    final slotMap = <String, TimeSlotModel>{};
    for (final s in LocalStorageService.getTimeSlots()) {
      slotMap[s.startTime] = s;
    }

    final now = DateTime.now();

    int count = 0;
    final batch = _db.batch();
    final List<DeliveryModel> localToSave = [];

    int routeOrder = LocalStorageService.getDeliveries()
        .where((d) => _isSameDate(d.scheduledDate, date))
        .length;

    for (final sub in subscriptions) {
      if (!sub.shouldDeliverOn(date)) continue;

      final customer = customerMap[sub.customerId];
      if (customer != null && customer.statusStr == 'inactive') continue;

      final address = customer?.address ?? '';

      for (final slotStartTime in sub.effectiveSlots) {
        // Time-gate: if generating for today and this slot hasn't opened yet, skip.
        // The engine will call generateForDateAndSlot when the window opens.
        if (onlyOpenOrPastSlots && _isSameDate(date, now)) {
          final slotModel = slotMap[slotStartTime];
          if (slotModel != null) {
            final slotStart = slotModel.getStartDateTime(date);
            if (now.isBefore(slotStart)) {
              AppLogger.d('GenerationService: Skipping future slot $slotStartTime — engine will handle it.');
              continue;
            }
          }
        }

        // DETERMINISTIC ID prevents duplicates across devices / re-runs
        final dateKey  = _formatDateKey(date);
        final safeSlot = slotStartTime.replaceAll(' ', '_').replaceAll(':', '');
        final deliveryId = '${sub.id}_${dateKey}_$safeSlot';

        if (_checkDeliveryExistsLocally(sub.id, date, slotStartTime)) continue;

        final slotTime = _slotToDateTime(date, slotStartTime);

        final delivery = DeliveryModel(
          id: deliveryId,
          vendorId: vendorId,
          customerId: sub.customerId,
          customerName: sub.customerName,
          customerAddress: address,
          subscriptionId: sub.id,
          serviceTypeStr: sub.serviceTypeStr,
          quantity: sub.quantity,
          unit: sub.unit,
          amount: sub.pricePerDelivery,
          scheduledDate: slotTime,
          deliverySlot: slotStartTime,
          routeOrder: routeOrder++,
          statusStr: DeliveryStatus.pending.name,
          isExtraOrder: false,
          isSynced: _connectivity.isOnline.value,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
          billGenerated: false,
          invoiceId: null,
        );

        localToSave.add(delivery);

        if (_connectivity.isOnline.value) {
          batch.set(
            _db.collection(_deliveriesCol(vendorId)).doc(delivery.id),
            delivery.toFirestore(),
            SetOptions(merge: true),
          );
        } else {
          _enqueueOfflineCreate(vendorId, delivery);
        }
        count++;
      }
    }

    if (_connectivity.isOnline.value && count > 0) {
      try {
        await batch.commit();
      } catch (e) {
        AppLogger.e('DeliveryGenerationService: batch commit failed, falling back to offline queue', e);
        for (final d in localToSave) {
          _enqueueOfflineCreate(vendorId, d..copyWith(isSynced: false));
        }
      }
    }

    for (final d in localToSave) {
      await LocalStorageService.saveDelivery(d);
    }

    if (count > 0) {
      AppLogger.i('GenerationService: Generated $count deliveries for ${_formatDateKey(date)}');
    }
    return count;
  }

  /// Called by the engine exactly when a slot window opens.
  /// Uses a deterministic ID so re-triggering within the 6-minute window is safe.
  Future<int> generateForDateAndSlot(String vendorId, DateTime date, String targetSlot) async {
    final subscriptions = LocalStorageService.getSubscriptions()
        .where((s) => s.isActive)
        .toList();

    if (subscriptions.isEmpty) return 0;

    final customerMap = {
      for (final c in LocalStorageService.getCustomers()) c.id: c,
    };

    int count = 0;
    final batch = _db.batch();
    final List<DeliveryModel> localToSave = [];

    for (final sub in subscriptions) {
      if (!sub.shouldDeliverOn(date)) continue;
      if (!sub.effectiveSlots.contains(targetSlot)) continue;

      final customer = customerMap[sub.customerId];
      if (customer != null && customer.statusStr == 'inactive') continue;

      // DETERMINISTIC ID — same formula as generateForDate so no duplicates
      final dateKey  = _formatDateKey(date);
      final safeSlot = targetSlot.replaceAll(' ', '_').replaceAll(':', '');
      final deliveryId = '${sub.id}_${dateKey}_$safeSlot';

      if (_checkDeliveryExistsLocally(sub.id, date, targetSlot)) continue;

      final slotTime = _slotToDateTime(date, targetSlot);

      final delivery = DeliveryModel(
        id: deliveryId,
        vendorId: vendorId,
        customerId: sub.customerId,
        customerName: sub.customerName,
        customerAddress: customer?.address ?? '',
        subscriptionId: sub.id,
        serviceTypeStr: sub.serviceTypeStr,
        quantity: sub.quantity,
        unit: sub.unit,
        amount: sub.pricePerDelivery,
        scheduledDate: slotTime,
        deliverySlot: targetSlot,
        routeOrder: 0,
        statusStr: DeliveryStatus.pending.name,
        isExtraOrder: false,
        isSynced: _connectivity.isOnline.value,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        billGenerated: false,
      );

      localToSave.add(delivery);
      if (_connectivity.isOnline.value) {
        batch.set(
          _db.collection(_deliveriesCol(vendorId)).doc(delivery.id),
          delivery.toFirestore(),
          SetOptions(merge: true),
        );
      } else {
        _enqueueOfflineCreate(vendorId, delivery);
      }
      count++;
    }

    if (_connectivity.isOnline.value && count > 0) {
      try {
        await batch.commit();
      } catch (e) {
        AppLogger.e('DeliveryGenerationService: slot batch commit failed', e);
        for (final d in localToSave) {
          _enqueueOfflineCreate(vendorId, d..copyWith(isSynced: false));
        }
      }
    }

    for (final d in localToSave) {
      await LocalStorageService.saveDelivery(d);
    }

    if (count > 0) {
      AppLogger.i('GenerationService: Generated $count deliveries for slot $targetSlot on ${_formatDateKey(date)}');
    }
    return count;
  }

  // ─────────────────────────────────────────────────────────────
  // HELPERS
  // ─────────────────────────────────────────────────────────────

  bool _checkDeliveryExistsLocally(String subscriptionId, DateTime date, String slot) {
    return LocalStorageService.getDeliveries().any((d) =>
    d.subscriptionId == subscriptionId &&
        d.deliverySlot == slot &&
        _isSameDate(d.scheduledDate, date));
  }

  void _enqueueOfflineCreate(String vendorId, DeliveryModel d) {
    LocalStorageService.enqueueSyncAction(SyncActionModel(
      id: const Uuid().v4(),
      actionTypeStr: SyncActionType.placeExtraOrder.name,
      collection: _deliveriesCol(vendorId),
      documentId: d.id,
      payload: d.toFirestore(),
      createdAt: DateTime.now(),
    ));
  }

  bool _isSameDate(DateTime a, DateTime b) =>
      a.year == b.year && a.month == b.month && a.day == b.day;

  String _formatDateKey(DateTime d) => '${d.year}-${d.month}-${d.day}';

  DateTime _slotToDateTime(DateTime baseDate, String slot) {
    final cleaned = slot.trim().toUpperCase();
    final parts   = cleaned.split(' ');

    if (parts.length != 2) {
      return DateTime(baseDate.year, baseDate.month, baseDate.day, 7, 0);
    }

    final timeParts = parts[0].split(':');
    int hour   = int.tryParse(timeParts[0]) ?? 7;
    int minute = timeParts.length > 1 ? (int.tryParse(timeParts[1]) ?? 0) : 0;

    if (parts[1] == 'PM' && hour != 12) hour += 12;
    if (parts[1] == 'AM' && hour == 12) hour = 0;

    return DateTime(baseDate.year, baseDate.month, baseDate.day, hour, minute);
  }
}