// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEZzEK71688GBOkb6BTswKbbvmbdQbqk0',
    appId: '1:966307386717:web:328a1bc699e1a33a86c4b4',
    messagingSenderId: '966307386717',
    projectId: 'e-commerce-sample-c5fbb',
    authDomain: 'e-commerce-sample-c5fbb.firebaseapp.com',
    storageBucket: 'e-commerce-sample-c5fbb.firebasestorage.app',
    measurementId: 'G-JL5Z5D001K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOVbNu2V4hJSbahnY_XhQdkv0Nlyr_WIw',
    appId: '1:966307386717:android:8bf19c9401bcf63786c4b4',
    messagingSenderId: '966307386717',
    projectId: 'e-commerce-sample-c5fbb',
    storageBucket: 'e-commerce-sample-c5fbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2pF6v_uqO2UpxSE2xYejTW1m2GsPCKJ4',
    appId: '1:966307386717:ios:c392b5412643f3b186c4b4',
    messagingSenderId: '966307386717',
    projectId: 'e-commerce-sample-c5fbb',
    storageBucket: 'e-commerce-sample-c5fbb.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceSuppliers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2pF6v_uqO2UpxSE2xYejTW1m2GsPCKJ4',
    appId: '1:966307386717:ios:c392b5412643f3b186c4b4',
    messagingSenderId: '966307386717',
    projectId: 'e-commerce-sample-c5fbb',
    storageBucket: 'e-commerce-sample-c5fbb.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceSuppliers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEZzEK71688GBOkb6BTswKbbvmbdQbqk0',
    appId: '1:966307386717:web:9006503aac84b52e86c4b4',
    messagingSenderId: '966307386717',
    projectId: 'e-commerce-sample-c5fbb',
    authDomain: 'e-commerce-sample-c5fbb.firebaseapp.com',
    storageBucket: 'e-commerce-sample-c5fbb.firebasestorage.app',
    measurementId: 'G-BKW0VMBZY2',
  );
}
