// lib/data/models/hive/hive_adapters.dart
//
// NOTE: In production, run `flutter pub run build_runner build`
// to generate the .g.dart adapter files from the @HiveType annotations.
//
// This file manually registers all adapters. Each models's .g.dart
// is auto-generated by hive_generator — do not write them by hand.

import 'package:hive/hive.dart';
import '../vendor_model.dart';
import '../customer_model.dart';
import '../subscription_model.dart';
import '../delivery_model.dart';
import '../sync_action_model.dart';

void registerHiveAdapters() {
  // Guard against double-registration during hot restart
  if (!Hive.isAdapterRegistered(0)) Hive.registerAdapter(VendorModelAdapter());
  if (!Hive.isAdapterRegistered(1)) Hive.registerAdapter(CustomerModelAdapter());
  if (!Hive.isAdapterRegistered(2)) Hive.registerAdapter(SubscriptionModelAdapter());
  if (!Hive.isAdapterRegistered(3)) Hive.registerAdapter(DeliveryModelAdapter());
  if (!Hive.isAdapterRegistered(4)) Hive.registerAdapter(SyncActionModelAdapter());
}